"""empty message

Revision ID: 7bb514930fae
Revises: d3256d13d29a
Create Date: 2025-05-01 00:46:37.788385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb514930fae'
down_revision = 'd3256d13d29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('passenger', sa.String(length=60), nullable=False),
    sa.Column('pilot', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starship_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'starship', ['starship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('starship_id')

    op.drop_table('starship')
    # ### end Alembic commands ###
